title: Default Page
preset: page
fields:
  text:
    label: Text
    type: textarea
    size: small

  headertitle:
    label: HEADER TITLE
    type: text
    size: small
  headertext:
    label: Header / Text
    type: textarea
    size: small

  featurestitle:
    label: FEATURES TITLE
    type: text
    size: small

  fonetitle:
    label: Feature title 1
    type: text
    size: small

  fonetext:
    label: Feature text 1
    type: text
    size: small

  ftwotitle:
    label: Feature title 2
    type: text
    size: small

  ftwotext:
    label: Feature text 2
    type: text
    size: small

  fthreetitle:
    label: Feature title 3
    type: text
    size: small

  fthreetext:
    label: Feature text 3
    type: text
    size: small

  ffourtitle:
    label: Feature title 4
    type: text
    size: small

  ffourtext:
    label: Feature text 4
    type: text
    size: small

  ffivetitle:
    label: Feature title 5
    type: text
    size: small

  ffivetext:
    label: Feature text 5
    type: text
    size: small

  fsixtitle:
    label: Feature title 6
    type: text
    size: small

  fsixtext:
    label: Feature text 6
    type: text
    size: small

  whytitle:
    label: WHY TITLE
    type: text
    size: small
  whytextone:
    label: Why / Text one
    type: textarea
    size: small
  whytexttwo:
    label: Why / Text two
    type: textarea
    size: small

  moretitle:
    label: MORE TITLE
    type: text
    size: small
  moretextone:
    label: More / Text one
    type: textarea
    size: small
  moretexttwo:
    label: More / Text two
    type: textarea
    size: small

  quotetext:
    label: QUOTE
    type: text
    size: small

  linksix:
    label: LINK 6
    type: url
    size: small

  video:
    label: VIDEO URL
    type: url
    size: small

  whotitle:
    label: WHO TITLE
    type: text
    size: small
  whotextone:
    label: Who / Text one
    type: textarea
    size: small
  whotexttwo:
    label: Who / Text two
    type: textarea
    size: small

  prosconstitle:
    label: PROS CONS TITLE
    type: text
    size: small

  prostitle:
    label: PROS title
    type: text
    size: small

  pros:
    label: PROS
    type: textarea
    size: small

  constitle:
    label: CONS title
    type: text
    size: small

  cons:
    label: CONS
    type: textarea
    size: small

  tutorialtitle:
    label: TUT TITLE
    type: text
    size: small
  tutorialtext:
    label: Tut / Text
    type: textarea
    size: small

  linktutorial:
    label: LINK TUT
    type: url
    size: small

  linkexample1:
    label: LINK EXAMPLE1
    type: url
    size: small

  linkexample2:
    label: LINK EXAMPLE2
    type: url
    size: small

  linkexample3:
    label: LINK EXAMPLE3
    type: url
    size: small

  linktwitter:
    label: LINK TWITTER
    type: url
    size: small

  linkfacebook:
    label: LINK FACEBOOK
    type: url
    size: small

  linkinstagram:
    label: LINK INSTAGRAM
    type: url
    size: small
